//! C++ code generator.
//!
//! Emits a single `.cpp` file that `#include "hs_runtime.hpp"` and wires the
//! parsed HardScript program into `hs::Server`, `hs::WsHandler`, crypto/fs/...
//! builtins, the test runner and `main()`.

use crate::ast::*;
use crate::error::{Diag, ErrorKind};
use crate::token::Span;

const MODULES: [&str; 10] = [
    "crypto", "fs", "env", "json", "jwt", "time", "runtime", "websocket", "postgres", "http",
];

const CPP_KEYWORDS: [&str; 61] = [
    "alignas", "alignof", "and", "and_eq", "asm", "auto", "bitand", "bitor", "bool", "break",
    "case", "catch", "char", "class", "compl", "const", "constexpr", "const_cast", "continue",
    "default", "delete", "do", "double", "dynamic_cast", "else", "enum", "explicit", "export",
    "extern", "false", "float", "for", "friend", "goto", "if", "inline", "int", "long", "mutable",
    "namespace", "new", "noexcept", "not", "not_eq", "nullptr", "operator", "or", "or_eq", "private",
    "protected", "public", "register", "reinterpret_cast", "return", "short", "signed", "sizeof",
    "static", "static_assert", "static_cast", "struct",
];

fn safe_id(name: &str) -> String {
    if CPP_KEYWORDS.contains(&name) {
        format!("{name}_")
    } else {
        name.to_string()
    }
}

fn cstring(s: &str) -> String {
    format!("{:?}", s)
}

struct Codegen {
    out: String,
    ind: usize,
    path: String,
    diags: Vec<Diag>,
}

/// Generate the C++ translation unit for `prog`.
pub fn generate(prog: &Program) -> Result<String, Vec<Diag>> {
    let mut cg = Codegen {
        out: String::new(),
        ind: 0,
        path: prog.path.clone(),
        diags: Vec::new(),
    };
    cg.run(prog);
    if cg.diags.is_empty() {
        Ok(cg.out)
    } else {
        Err(cg.diags)
    }
}

impl Codegen {
    fn w(&mut self, s: &str) {
        self.out.push_str(s);
    }
    fn wln(&mut self, s: &str) {
        for _ in 0..self.ind {
            self.out.push_str("    ");
        }
        self.out.push_str(s);
        self.out.push('\n');
    }
    fn blank(&mut self) {
        self.out.push('\n');
    }
    fn err(&mut self, msg: impl Into<String>, span: Span) {
        self.diags.push(Diag::new(
            ErrorKind::Codegen,
            msg,
            span,
            "This construct is not supported by the compiler yet.",
        ));
    }

    fn run(&mut self, prog: &Program) {
        self.w("// Generated by the HardScript compiler — do not edit.\n");
        self.wln("#include \"hs_runtime.hpp\"");
        self.wln("using namespace hs;");
        self.wln("using std::string;");
        self.blank();

        let mut routes: Vec<&RouteDef> = Vec::new();
        let mut funcs: Vec<&FunDef> = Vec::new();
        let mut mws: Vec<String> = Vec::new();
        let mut mw_bodies: Vec<&Vec<Stmt>> = Vec::new();
        let mut sockets: Vec<&SocketDef> = Vec::new();
        let mut tests: Vec<&TestDef> = Vec::new();

        for st in &prog.stmts {
            match st {
                Stmt::Var(v) | Stmt::Const(v) => {
                    let val = self.expr(&v.value);
                    let n = safe_id(&v.name);
                    let line = format!("hs::Val {n} = {val};");
                    self.wln(&line);
                }
                Stmt::Func(f) => funcs.push(f),
                Stmt::Route(r) => routes.push(r),
                Stmt::Middleware { name, body, .. } => {
                    mws.push(name.clone());
                    mw_bodies.push(body);
                }
                Stmt::Socket(s) => sockets.push(s),
                Stmt::Test(t) => tests.push(t),
                _ => {}
            }
        }

        for f in &funcs {
            self.emit_func(f);
        }
        for (i, r) in routes.iter().enumerate() {
            self.emit_route(r, i);
        }
        for (i, (name, body)) in mws.iter().zip(mw_bodies.iter()).enumerate() {
            self.emit_middleware(name, body, i);
        }

        let port = prog
            .stmts
            .iter()
            .find_map(|s| match s {
                Stmt::App(p, _) => Some(*p),
                _ => None,
            })
            .unwrap_or(3000);

        self.emit_socket_registrations(&sockets);
        self.emit_test_registrations(&tests);
        self.emit_main(
            port,
            &routes,
            mws.len(),
            sockets.len(),
            tests.len(),
        );
    }

    fn emit_func(&mut self, f: &FunDef) {
        let mut args = String::new();
        for (i, p) in f.params.iter().enumerate() {
            if i > 0 {
                args.push_str(", ");
            }
            args.push_str(&format!("const hs::Val& {}", safe_id(&p.name)));
        }
        let line = format!("static hs::Val fn_{}({}) {{", safe_id(&f.name), args);
        self.wln(&line);
        self.ind += 1;
        self.stmts(&f.body, Ctx::Func);
        self.wln("return hs::Val::nil();");
        self.ind -= 1;
        self.wln("}");
        self.blank();
    }

    fn emit_route(&mut self, r: &RouteDef, idx: usize) {
        let line = format!("static hs::Response route_{idx}(const hs::Request& req) {{");
        self.wln(&line);
        self.ind += 1;
        self.wln("try {");
        self.ind += 1;
        for p in &r.params {
            let nm = safe_id(&p.name);
            if p.is_body {
                let l = format!("hs::Val {nm} = req.json();");
                self.wln(&l);
            } else {
                self.wln(&format!("hs::Val {nm} = [&]() -> hs::Val {{"));
                self.ind += 1;
                self.wln(&format!(
                    "auto __it = req.params.find({});",
                    cstring(&p.name)
                ));
                self.wln("if (__it != req.params.end()) return hs::Val::text(std::string(__it->second));");
                self.wln(&format!("std::string __q = req.q({});", cstring(&p.name)));
                self.wln("if (!__q.empty()) return hs::Val::text(__q);");
                self.wln("return hs::Val::nil();");
                self.ind -= 1;
                self.wln("}();");
            }
        }
        self.stmts(&r.body, Ctx::Route);
        self.wln("return hs::Response::error(500, \"route reached the end without returning a value\");");
        self.ind -= 1;
        self.wln("} catch (const std::exception& e) {");
        self.ind += 1;
        self.wln("return hs::Response::error(500, std::string(\"route error: \") + e.what());");
        self.ind -= 1;
        self.wln("}");
        self.ind -= 1;
        self.wln("}");
        self.blank();
    }

    fn emit_middleware(&mut self, name: &str, body: &[Stmt], idx: usize) {
        let _ = name;
        let line = format!(
            "static hs::Response mw_{idx}(const hs::Request& req, const std::function<hs::Response()>& next) {{"
        );
        self.wln(&line);
        self.ind += 1;
        self.wln("try {");
        self.ind += 1;
        self.stmts(body, Ctx::Middleware);
        self.wln("return next();");
        self.ind -= 1;
        self.wln("} catch (const std::exception& e) {");
        self.ind += 1;
        self.wln("return hs::Response::error(500, std::string(\"middleware error: \") + e.what());");
        self.ind -= 1;
        self.wln("}");
        self.ind -= 1;
        self.wln("}");
        self.blank();
    }

    fn emit_socket_registrations(&mut self, sockets: &[&SocketDef]) {
        for (k, s) in sockets.iter().enumerate() {
            let line = format!("static bool ws_registered_{k} = false;");
            self.wln(&line);
            let line = format!(
                "static void register_ws_{k}() {{ if (ws_registered_{k}) return; ws_registered_{k} = true;"
            );
            self.wln(&line);
            self.ind += 1;
            self.wln("hs::WsHandler __w;");
            let line = format!("__w.path = {};", cstring(&s.path));
            self.wln(&line);
            if let Some(body) = &s.connect {
                self.wln("__w.on_open = [](const hs::Request&) {");
                self.ind += 1;
                self.stmts(body, Ctx::Ws);
                self.ind -= 1;
                self.wln("};");
            }
            if let Some(body) = &s.message {
                self.wln("__w.on_msg = [](const std::string& __payload, bool) {");
                self.ind += 1;
                self.wln("hs::Val d = hs::Val::text(__payload);");
                self.stmts(body, Ctx::Ws);
                self.ind -= 1;
                self.wln("};");
            }
            if let Some(body) = &s.disconnect {
                self.wln("__w.on_close = []() {");
                self.ind += 1;
                self.stmts(body, Ctx::Ws);
                self.ind -= 1;
                self.wln("};");
            }
            self.wln("hs::ws_registry().push_back(std::move(__w));");
            self.ind -= 1;
            self.wln("}");
            self.blank();
        }
    }

    fn emit_test_registrations(&mut self, tests: &[&TestDef]) {
        for (k, t) in tests.iter().enumerate() {
            let line = format!("static bool test_registered_{k} = false;");
            self.wln(&line);
            let line = format!(
                "static void register_test_{k}() {{ if (test_registered_{k}) return; test_registered_{k} = true;"
            );
            self.wln(&line);
            self.ind += 1;
            let name = cstring(&t.name);
            let line = format!("hs::register_test({name}, []() {{");
            self.wln(&line);
            self.ind += 1;
            self.stmts(&t.body, Ctx::Test);
            self.ind -= 1;
            self.wln("});");
            self.ind -= 1;
            self.wln("}");
            self.blank();
        }
    }

    fn emit_main(&mut self, port: i64, routes: &[&RouteDef], nmw: usize, nws: usize, ntests: usize) {
        self.wln("int main(int argc, char** argv) {");
        self.ind += 1;
        self.wln("hs::set_args(argc, argv);");
        self.wln("hs::Server app;");
        self.wln("hs::hs_set_server(&app);");
        for i in 0..nmw {
            let line = format!("app.before(mw_{i});");
            self.wln(&line);
        }
        for (i, r) in routes.iter().enumerate() {
            let line = format!(
                "app.handle({}, {}, route_{i});",
                cstring(&r.method),
                cstring(&r.path)
            );
            self.wln(&line);
        }
        let line = format!("app.port = {port};");
        self.wln(&line);
        self.blank();
        for i in 0..nws {
            let line = format!("register_ws_{i}();");
            self.wln(&line);
        }
        for i in 0..ntests {
            let line = format!("register_test_{i}();");
            self.wln(&line);
        }
        if ntests > 0 {
            self.wln("if (hs::want_test()) return app.test_main();");
        }
        self.wln("app.listen();");
        self.wln("return 0;");
        self.ind -= 1;
        self.wln("}");
    }

    // ---------- statements ----------

    fn stmts(&mut self, body: &[Stmt], ctx: Ctx) {
        for st in body {
            self.stmt(st, ctx);
        }
    }

    fn stmt(&mut self, st: &Stmt, ctx: Ctx) {
        match st {
            Stmt::Bring(..) | Stmt::App(..) | Stmt::Model(..) => {}
            Stmt::Func(_) | Stmt::Route(_) | Stmt::Middleware { .. } | Stmt::Socket(_)
            | Stmt::Test(_) => {}
            Stmt::Var(v) => {
                let val = self.expr(&v.value);
                let line = format!("hs::Val {} = {val};", safe_id(&v.name));
                self.wln(&line);
            }
            Stmt::Const(v) => {
                let val = self.expr(&v.value);
                let line = format!("hs::Val {} = {val};", safe_id(&v.name));
                self.wln(&line);
            }
            Stmt::If { cond, then_body, else_body, .. } => {
                let c = self.expr(cond);
                let line = format!("if ({c} .truthy()) {{");
                self.wln(&line);
                self.ind += 1;
                self.stmts(then_body, ctx);
                self.ind -= 1;
                if else_body.is_empty() {
                    self.wln("}");
                } else {
                    self.wln("} else {");
                    self.ind += 1;
                    self.stmts(else_body, ctx);
                    self.ind -= 1;
                    self.wln("}");
                }
            }
            Stmt::Loop { var, iter, body, .. } => {
                let v = safe_id(var);
                if let Expr::Range(lo, hi, _) = iter {
                    let l = self.expr(lo);
                    let h = self.expr(hi);
                    let line = format!(
                        "for (hs::Val {v} = {l}; {v}.iv <= {h} .iv; {v} = hs::op_add({v}, hs::Val::int_(1))) {{"
                    );
                    self.wln(&line);
                    self.ind += 1;
                    self.stmts(body, ctx);
                    self.ind -= 1;
                    self.wln("}");
                } else {
                    let it = self.expr(iter);
                    self.wln("{ /* loop over iterable */");
                    self.ind += 1;
                    let line = format!("hs::Val __it = {it};");
                    self.wln(&line);
                    self.wln("if (__it.is_arr()) {");
                    self.ind += 1;
                    self.wln("for (size_t __n = 0; __n < __it.arr.size(); __n++) {");
                    self.ind += 1;
                    let line = format!("hs::Val {v} = __it.atc(__n);");
                    self.wln(&line);
                    self.stmts(body, ctx);
                    self.ind -= 1;
                    self.wln("}");
                    self.ind -= 1;
                    self.wln("} else if (__it.is_str()) {");
                    self.ind += 1;
                    self.wln("for (size_t __n = 0; __n < __it.sv.size(); __n++) {");
                    self.ind += 1;
                    let line = format!("hs::Val {v} = hs::Val::text(std::string(1, __it.sv[__n]));");
                    self.wln(&line);
                    self.stmts(body, ctx);
                    self.ind -= 1;
                    self.wln("}");
                    self.ind -= 1;
                    self.wln("} else {");
                    self.ind += 1;
                    let line = format!("hs::Val {v} = __it;");
                    self.wln(&line);
                    self.stmts(body, ctx);
                    self.ind -= 1;
                    self.wln("}");
                    self.ind -= 1;
                    self.wln("}");
                }
            }
            Stmt::Return(expr, _) => match ctx {
                Ctx::Func => {
                    let val = self.expr(expr);
                    let line = format!("return {val};");
                    self.wln(&line);
                }
                Ctx::Route | Ctx::Middleware => {
                    let val = self.expr(expr);
                    let line = format!("return hs::hs_respond({val});");
                    self.wln(&line);
                }
                Ctx::Test | Ctx::Ws => self.wln("return;"),
            },
            Stmt::Race(exprs, _) => {
                let mut tasks = String::from("{ ");
                for (i, e) in exprs.iter().enumerate() {
                    if i > 0 {
                        tasks.push_str(", ");
                    }
                    let v = self.expr(e);
                    tasks.push_str(&format!("[]() -> hs::Val {{ return {v}; }}"));
                }
                tasks.push_str(" }");
                let line = format!("(void)hs::race_val({tasks});");
                self.wln(&line);
            }
            Stmt::Expect { lhs, op, rhs, span } => {
                let cond = {
                    let c = self.binwrap(op, lhs, rhs);
                    format!("{c} .bv")
                };
                let what = format!(
                    "expect {} {} {}",
                    self.src_expr(lhs),
                    op.symbol(),
                    self.src_expr(rhs)
                );
                let where_ = format!("{}:{}", self.path, span.line);
                let line = format!("hs::expect({cond}, {:?}, {:?});", what, where_);
                self.wln(&line);
            }
            Stmt::ExprStmt(e) => {
                let cpp = self.expr(e);
                if !cpp.is_empty() {
                    let line = format!("(void)({cpp});");
                    self.wln(&line);
                }
            }
        }
    }

    fn binwrap(&mut self, op: &BinOp, lhs: &Expr, rhs: &Expr) -> String {
        let l = self.expr(lhs);
        let r = self.expr(rhs);
        let f = match op {
            BinOp::Add => "hs::op_add",
            BinOp::Sub => "hs::op_sub",
            BinOp::Mul => "hs::op_mul",
            BinOp::Div => "hs::op_div",
            BinOp::Mod => "hs::op_mod",
            BinOp::Eq => "hs::op_eq",
            BinOp::Ne => "hs::op_ne",
            BinOp::Lt => "hs::op_lt",
            BinOp::Le => "hs::op_le",
            BinOp::Gt => "hs::op_gt",
            BinOp::Ge => "hs::op_ge",
            BinOp::And => "hs::op_and",
            BinOp::Or => "hs::op_or",
        };
        format!("{f}({l}, {r})")
    }

    // ---------- expressions ----------

    fn expr(&mut self, e: &Expr) -> String {
        match e {
            Expr::Int(n, _) => format!("hs::Val::int_({n})"),
            Expr::Float(f, _) => {
                if *f == (*f).trunc() {
                    format!("hs::Val::flt({f}.0)")
                } else {
                    format!("hs::Val::flt({f})")
                }
            }
            Expr::Str(s, _) => format!("hs::Val::text({:?})", s),
            Expr::Bool(b, _) => format!("hs::Val::boolean({b})"),
            Expr::List(items, _) => {
                let mut inner = String::new();
                for (i, it) in items.iter().enumerate() {
                    if i > 0 {
                        inner.push_str(", ");
                    }
                    inner.push_str(&self.expr(it));
                }
                format!("hs::Val::list(std::vector<hs::Val>{{ {inner} }})")
            }
            Expr::Obj(kvs, _) => {
                let mut inner = String::new();
                for (i, (k, v)) in kvs.iter().enumerate() {
                    if i > 0 {
                        inner.push_str(", ");
                    }
                    let v = self.expr(v);
                    inner.push_str(&format!("{{\"{}\", {v}}}", k));
                }
                format!("hs::Val::object({{ {inner} }})")
            }
            Expr::Ident(name, _) => safe_id(name),
            Expr::Member(base, name, sp) => {
                if let Expr::Ident(module, _) = base.as_ref() {
                    if MODULES.contains(&module.as_str()) {
                        if let Some(r) = self.builtin(module, name, &[], *sp) {
                            return r;
                        }
                    }
                }
                let b = self.expr(base);
                format!("hs::get_member({b}, {:?})", name)
            }
            Expr::Index(base, idx, _) => {
                let b = self.expr(base);
                let i = self.expr(idx);
                format!("hs::index_at({b}, {i})")
            }
            Expr::Call { callee, args, span } => self.call(callee, args, *span),
            Expr::Unary(op, inner, _) => {
                let i = self.expr(inner);
                match op {
                    UnOp::Neg => format!("hs::op_neg({i})"),
                    UnOp::Not => format!("hs::Val::boolean(!{i} .truthy())"),
                }
            }
            Expr::Binary(op, l, r, _) => self.binwrap(op, l, r),
            Expr::Range(_, _, sp) => {
                self.err("range used outside a loop", *sp);
                "hs::Val::nil()".to_string()
            }
            Expr::Match(scrut, arms, _) => {
                let s = self.expr(scrut);
                let mut out = String::from("([](const hs::Val& __m) -> hs::Val {");
                for arm in arms {
                    if let Some(val) = &arm.value {
                        let v = self.expr(val);
                        let b = self.expr(&arm.body);
                        out.push_str(&format!(" if (hs::op_eq(__m, {v}).bv) return {b};"));
                    } else {
                        let b = self.expr(&arm.body);
                        out.push_str(&format!(" return {b};"));
                    }
                }
                out.push_str(" return hs::Val::nil(); })(");
                out.push_str(&s);
                out.push(')');
                out
            }
            Expr::HttpCall { verb, path, body, .. } => {
                let b = match body {
                    Some(b) => self.expr(b),
                    None => "hs::Val::object({})".to_string(),
                };
                format!("hs::test_call({:?}, {:?}, {b})", verb, path)
            }
        }
    }

    fn call(&mut self, callee: &Expr, args: &[Expr], span: Span) -> String {
        match callee {
            Expr::Member(base, name, _) => {
                if let Expr::Ident(module, _) = base.as_ref() {
                    if MODULES.contains(&module.as_str()) {
                        if let Some(r) = self.builtin(module, name, args, span) {
                            return r;
                        }
                    }
                }
                let b = self.expr(base);
                format!("hs::get_member({b}, {:?})", name)
            }
            Expr::Ident(name, _) => {
                if name == "_" {
                    return "hs::Val::nil()".to_string();
                }
                let args_cpp: Vec<String> = args.iter().map(|a| self.expr(a)).collect();
                // User calc functions are emitted as global `static ... fn_x` in
                // the generated TU, so call them unqualified (`using namespace
                // hs;` is active at that point). `hs::fn_x` would not resolve.
                format!("fn_{}({})", safe_id(name), args_cpp.join(", "))
            }
            _ => {
                self.err("cannot call this expression", span);
                "hs::Val::nil()".to_string()
            }
        }
    }

    fn arg_at(&mut self, args: &[Expr], i: usize) -> String {
        if i < args.len() {
            self.expr(&args[i])
        } else {
            "hs::Val::nil()".to_string()
        }
    }

    fn ttx(&mut self, args: &[Expr], i: usize) -> String {
        let v = self.arg_at(args, i);
        format!("hs::to_text({v}).sv")
    }

    fn tin(&mut self, args: &[Expr], i: usize) -> String {
        let v = self.arg_at(args, i);
        format!("hs::to_int({v}).iv")
    }

    fn builtin(&mut self, module: &str, name: &str, args: &[Expr], span: Span) -> Option<String> {
        match (module, name) {
            // crypto
            (_, _) if module == "crypto" && name == "sha256" => {
                Some(format!("hs::Val::text(hs::sha256_hex({}))", self.ttx(args, 0)))
            }
            (_, _) if module == "crypto" && name == "sha256bin" => {
                Some(format!("hs::Val::text(hs::sha256_bin({}))", self.ttx(args, 0)))
            }
            (_, _) if module == "crypto" && name == "sha1" => {
                Some(format!("hs::Val::text(hs::sha1_hex({}))", self.ttx(args, 0)))
            }
            (_, _) if module == "crypto" && name == "md5" => {
                Some(format!("hs::Val::text(hs::md5_hex({}))", self.ttx(args, 0)))
            }
            (_, _) if module == "crypto" && name == "hmac" => {
                let a = self.ttx(args, 0);
                let b = self.ttx(args, 1);
                Some(format!("hs::Val::text(hs::hmac_sha256_bin({a}, {b}))"))
            }
            (_, _) if module == "crypto" && name == "base64" => {
                Some(format!("hs::Val::text(hs::base64_encode({}))", self.ttx(args, 0)))
            }
            (_, _) if module == "crypto" && name == "base64url" => {
                Some(format!(
                    "hs::Val::text(hs::base64_encode_url({}))",
                    self.ttx(args, 0)
                ))
            }
            (_, _) if module == "crypto" && name == "base64decode" => {
                Some(format!(
                    "hs::Val::text(hs::base64_decode({}))",
                    self.ttx(args, 0)
                ))
            }
            (_, _) if module == "crypto" && name == "uuid" => {
                Some("hs::Val::text(hs::random_uuid())".to_string())
            }
            (_, _) if module == "crypto" && name == "random_hex" => {
                Some(format!("hs::Val::text(hs::random_hex({}))", self.tin(args, 0)))
            }
            (_, _) if module == "crypto" && name == "token" => {
                Some(format!(
                    "hs::Val::text(hs::random_urlsafe({}))",
                    self.tin(args, 0)
                ))
            }
            // json
            (_, _) if module == "json" && name == "parse" => {
                Some(format!("hs::parse_json({})", self.ttx(args, 0)))
            }
            (_, _) if module == "json" && name == "stringify" => {
                Some(format!("hs::Val::text(hs::to_json({}))", self.arg_at(args, 0)))
            }
            (_, _) if module == "json" && name == "keys" => {
                let a = self.arg_at(args, 0);
                Some(format!(
                    "hs::Val::list([](const hs::Val& __o) {{ std::vector<hs::Val> __v; for (auto& __kv : __o.obj) __v.push_back(hs::Val::text(__kv.first)); return __v; }}({a}))"
                ))
            }
            // env
            (_, _) if module == "env" && name == "get" => {
                Some(format!("hs::Val::text(hs::env_get({}))", self.ttx(args, 0)))
            }
            // fs
            (_, _) if module == "fs" && name == "read" => {
                Some(format!("hs::Val::text(hs::fs_read({}))", self.ttx(args, 0)))
            }
            (_, _) if module == "fs" && name == "write" => {
                let a = self.ttx(args, 0);
                let b = self.ttx(args, 1);
                Some(Self::void_expr(format!("hs::fs_write({a}, {b})")))
            }
            (_, _) if module == "fs" && name == "append" => {
                let a = self.ttx(args, 0);
                let b = self.ttx(args, 1);
                Some(Self::void_expr(format!("hs::fs_append({a}, {b})")))
            }
            (_, _) if module == "fs" && name == "exists" => {
                Some(format!("hs::Val::boolean(hs::fs_exists({}))", self.ttx(args, 0)))
            }
            (_, _) if module == "fs" && name == "is_dir" => {
                Some(format!("hs::Val::boolean(hs::fs_is_dir({}))", self.ttx(args, 0)))
            }
            (_, _) if module == "fs" && name == "list" => {
                let a = self.ttx(args, 0);
                Some(format!(
                    "([](const std::vector<std::string>& __v) {{ std::vector<hs::Val> __r; for (auto& __s : __v) __r.push_back(hs::Val::text(__s)); return hs::Val::list(__r); }}(hs::fs_list({a})))"
                ))
            }
            (_, _) if module == "fs" && name == "remove" => {
                Some(Self::void_expr(format!("hs::fs_remove({})", self.ttx(args, 0))))
            }
            (_, _) if module == "fs" && name == "size" => {
                Some(format!("hs::Val::int_(hs::fs_size({}))", self.ttx(args, 0)))
            }
            // jwt
            (_, _) if module == "jwt" && name == "sign" => {
                let a = self.arg_at(args, 0);
                let b = self.ttx(args, 1);
                Some(format!("hs::Val::text(hs::jwt_sign({a}, {b}))"))
            }
            (_, _) if module == "jwt" && name == "verify" => {
                let a = self.ttx(args, 0);
                let b = self.ttx(args, 1);
                Some(format!("hs::Val::boolean(hs::jwt_verify({a}, {b}))"))
            }
            // time
            (_, _) if module == "time" && name == "now" => {
                Some("hs::Val::int_(hs::unix_ms())".to_string())
            }
            (_, _) if module == "time" && name == "iso" => {
                Some("hs::Val::text(hs::time_iso())".to_string())
            }
            (_, _) if module == "time" && name == "sleep" => {
                let a = self.arg_at(args, 0);
                Some(Self::void_expr(format!("hs::sleep_sec({a} .num())")))
            }
            // runtime
            (_, _) if module == "runtime" && name == "args" => {
                Some("hs::args_list()".to_string())
            }
            (_, _) if module == "runtime" && name == "argc" => {
                Some("hs::Val::int_(hs::argc())".to_string())
            }
            (_, _) if module == "runtime" && name == "argv" => {
                Some(format!("hs::Val::text(hs::argv({}))", self.tin(args, 0)))
            }
            (_, _) if module == "runtime" && name == "print" => {
                Some(format!("hs::v_print({})", self.arg_at(args, 0)))
            }
            (_, _) if module == "runtime" && name == "pid" => {
                Some("hs::Val::text(hs::pid())".to_string())
            }
            (_, _) if module == "runtime" && name == "hostname" => {
                Some("hs::Val::text(hs::hostname())".to_string())
            }
            (_, _) if module == "runtime" && name == "platform" => {
                Some("hs::Val::text(hs::platform())".to_string())
            }
            (_, _) if module == "runtime" && name == "cpus" => {
                Some("hs::Val::int_(hs::cpus())".to_string())
            }
            // websocket
            (_, _) if module == "websocket" && name == "broadcast" => {
                Some(Self::void_expr(format!("hs::ws_broadcast({})", self.ttx(args, 0))))
            }
            (_, _) if module == "websocket" && name == "broadcast_room" => {
                let a = self.ttx(args, 0);
                let b = self.ttx(args, 1);
                Some(Self::void_expr(format!("hs::ws_broadcast_room({a}, {b})")))
            }
            (_, _) if module == "websocket" && name == "reply" => {
                Some(Self::void_expr(format!("hs::ws_reply({})", self.ttx(args, 0))))
            }
            (_, _) if module == "websocket" && name == "join" => {
                Some(Self::void_expr(format!(
                    "hs::ws_join(hs::ws_self(), {})",
                    self.ttx(args, 0)
                )))
            }
            (_, _) if module == "websocket" && name == "leave" => {
                Some(Self::void_expr("hs::ws_leave(hs::ws_self())".to_string()))
            }
            (_, _) if module == "websocket" && name == "self" => {
                Some("hs::Val::text(hs::ws_self())".to_string())
            }
            // postgres
            (_, _) if module == "postgres" && name == "connect" => {
                Some(format!("hs::Val::int_(hs::pg_connect({}))", self.ttx(args, 0)))
            }
            (_, _) if module == "postgres" && name == "query" => {
                let fd = self.tin(args, 0);
                let sql = self.ttx(args, 1);
                Some(format!("hs::pg_query({fd}, {sql})"))
            }
            _ => {
                let _ = span;
                self.err(format!("unknown builtin `{module}.{name}`"), span);
                Some("hs::Val::nil()".to_string())
            }
        }
    }

    fn void_expr(body: String) -> String {
        format!("([&]() -> hs::Val {{ {body}; return hs::Val::nil(); }}())")
    }

    // ---------- source-ish rendering for diagnostics / expect ----------

    fn src_expr(&self, e: &Expr) -> String {
        match e {
            Expr::Int(n, _) => n.to_string(),
            Expr::Float(f, _) => f.to_string(),
            Expr::Str(s, _) => format!("\"{}\"", s),
            Expr::Bool(b, _) => b.to_string(),
            Expr::List(items, _) => format!(
                "[{}]",
                items
                    .iter()
                    .map(|i| self.src_expr(i))
                    .collect::<Vec<_>>()
                    .join(", ")
            ),
            Expr::Obj(kvs, _) => format!(
                "{{ {} }}",
                kvs.iter()
                    .map(|(k, v)| format!("{k}: {}", self.src_expr(v)))
                    .collect::<Vec<_>>()
                    .join(", ")
            ),
            Expr::Ident(n, _) => n.clone(),
            Expr::Member(b, n, _) => format!("{}.{}", self.src_expr(b), n),
            Expr::Index(b, i, _) => format!("{}[{}]", self.src_expr(b), self.src_expr(i)),
            Expr::Call { callee, args, .. } => format!(
                "{}({})",
                self.src_expr(callee),
                args.iter().map(|a| self.src_expr(a)).collect::<Vec<_>>().join(", ")
            ),
            Expr::Unary(UnOp::Neg, x, _) => format!("-{}", self.src_expr(x)),
            Expr::Unary(UnOp::Not, x, _) => format!("!{}", self.src_expr(x)),
            Expr::Binary(op, l, r, _) => {
                format!("{} {} {}", self.src_expr(l), op.symbol(), self.src_expr(r))
            }
            Expr::Range(l, h, _) => format!("{}...{}", self.src_expr(l), self.src_expr(h)),
            Expr::Match(_, _, _) => "pick(..)".to_string(),
            Expr::HttpCall { verb, path, .. } => format!("{verb} \"{path}\""),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Ctx {
    Func,
    Route,
    Middleware,
    Ws,
    Test,
}