// Generated by the HardScript compiler — do not edit.
#include "hs_runtime.hpp"
using namespace hs;
using std::string;

static hs::Response route_0(const hs::Request& req) {
    try {
        hs::Val id = [&]() -> hs::Val {
            auto __it = req.params.find("id");
            if (__it != req.params.end()) return hs::Val::text(std::string(__it->second));
            std::string __q = req.q("id");
            if (!__q.empty()) return hs::Val::text(__q);
            return hs::Val::nil();
        }();
        return hs::hs_respond(hs::op_add(hs::Val::text("u-"), id));
        return hs::Response::error(500, "route reached the end without returning a value");
    } catch (const hs::HttpAbort& a) {
        return a.r;
    } catch (const std::exception& e) {
        return hs::Response::error(500, std::string("route error: ") + e.what());
    }
}

int main(int argc, char** argv) {
    hs::set_args(argc, argv);
    hs::Server app;
    hs::hs_set_server(&app);
    app.handle("GET", "/u/:id", route_0);
    app.port = 3031;

    app.listen();
    return 0;
}
