// Generated by the HardScript compiler — do not edit.
#include "hs_runtime.hpp"
using namespace hs;
using std::string;

static hs::Val fn_add(const hs::Val& a, const hs::Val& b) {
    return hs::op_add(a, b);
    return hs::Val::nil();
}

static hs::Val fn_fib(const hs::Val& n) {
    if (hs::op_lt(n, hs::Val::int_(2)) .truthy()) {
        return n;
    }
    return hs::op_add(fn_fib(hs::op_sub(n, hs::Val::int_(1))), fn_fib(hs::op_sub(n, hs::Val::int_(2))));
    return hs::Val::nil();
}

static hs::Response route_0(const hs::Request& req) {
    try {
        return hs::hs_respond(fn_add(hs::Val::int_(20), hs::Val::int_(22)));
        return hs::Response::error(500, "route reached the end without returning a value");
    } catch (const hs::HttpAbort& a) {
        return a.r;
    } catch (const std::exception& e) {
        return hs::Response::error(500, std::string("route error: ") + e.what());
    }
}

static hs::Response route_1(const hs::Request& req) {
    try {
        return hs::hs_respond(fn_fib(hs::Val::int_(10)));
        return hs::Response::error(500, "route reached the end without returning a value");
    } catch (const hs::HttpAbort& a) {
        return a.r;
    } catch (const std::exception& e) {
        return hs::Response::error(500, std::string("route error: ") + e.what());
    }
}

int main(int argc, char** argv) {
    hs::set_args(argc, argv);
    hs::Server app;
    hs::hs_set_server(&app);
    app.handle("GET", "/add", route_0);
    app.handle("GET", "/fib", route_1);
    app.port = hs::port_from_env(3031);

    app.listen();
    return 0;
}
