// Generated by the HardScript compiler — do not edit.
#include "hs_runtime.hpp"
using namespace hs;
using std::string;

hs::Val k = hs::Val::text("k");
hs::Val v = hs::Val::int_(40);
static hs::Response route_0(const hs::Request& req) {
    try {
        return hs::hs_respond(hs::op_add(v, hs::Val::int_(2)));
        return hs::Response::error(500, "route reached the end without returning a value");
    } catch (const std::exception& e) {
        return hs::Response::error(500, std::string("route error: ") + e.what());
    }
}

int main(int argc, char** argv) {
    hs::set_args(argc, argv);
    hs::Server app;
    hs::hs_set_server(&app);
    app.handle("GET", "/", route_0);
    app.port = 3031;

    app.listen();
    return 0;
}
