// Generated by the HardScript compiler — do not edit.
#include "hs_runtime.hpp"
using namespace hs;
using std::string;

static hs::Response route_0(const hs::Request& req) {
    try {
        return hs::hs_respond(hs::Val::text(hs::sha256_bin(hs::to_text(hs::Val::text("abc")).sv)));
        return hs::Response::error(500, "route reached the end without returning a value");
    } catch (const hs::HttpAbort& a) {
        return a.r;
    } catch (const std::exception& e) {
        return hs::Response::error(500, std::string("route error: ") + e.what());
    }
}

static hs::Response route_1(const hs::Request& req) {
    try {
        return hs::hs_respond(hs::Val::text(hs::to_json(hs::Val::object({ {"a", hs::Val::int_(1)} }))));
        return hs::Response::error(500, "route reached the end without returning a value");
    } catch (const hs::HttpAbort& a) {
        return a.r;
    } catch (const std::exception& e) {
        return hs::Response::error(500, std::string("route error: ") + e.what());
    }
}

int main(int argc, char** argv) {
    hs::set_args(argc, argv);
    hs::Server app;
    hs::hs_set_server(&app);
    app.handle("GET", "/crypto", route_0);
    app.handle("GET", "/json", route_1);
    app.port = 3031;

    app.listen();
    return 0;
}
