// Generated by the HardScript compiler — do not edit.
#include "hs_runtime.hpp"
using namespace hs;
using std::string;

static hs::Response route_0(const hs::Request& req) {
    try {
        return hs::hs_respond(hs::Val::text("ok"));
        return hs::Response::error(500, "route reached the end without returning a value");
    } catch (const hs::HttpAbort& a) {
        return a.r;
    } catch (const std::exception& e) {
        return hs::Response::error(500, std::string("route error: ") + e.what());
    }
}

static hs::Response mw_0(const hs::Request& req, const std::function<hs::Response()>& next) {
    try {
        if (hs::Val::boolean(false) .truthy()) {
            return hs::hs_respond(hs::Val::object({ {"error", hs::Val::text("denied")} }));
        }
        return next();
    } catch (const hs::HttpAbort& a) {
        return a.r;
    } catch (const std::exception& e) {
        return hs::Response::error(500, std::string("middleware error: ") + e.what());
    }
}

int main(int argc, char** argv) {
    hs::set_args(argc, argv);
    hs::Server app;
    hs::hs_set_server(&app);
    app.before(mw_0);
    app.handle("GET", "/", route_0);
    app.port = hs::port_from_env(3031);

    app.listen();
    return 0;
}
