// Generated by the HardScript compiler — do not edit.
#include "hs_runtime.hpp"
using namespace hs;
using std::string;

static hs::Response route_0(const hs::Request& req) {
    try {
        hs::Val t = hs::Val::int_(0);
        { /* loop over iterable */
            hs::Val __it = hs::Val::list(std::vector<hs::Val>{ hs::Val::int_(1), hs::Val::int_(2), hs::Val::int_(3), hs::Val::int_(4) });
            if (__it.is_arr()) {
                for (size_t __n = 0; __n < __it.arr.size(); __n++) {
                    hs::Val x = __it.atc(__n);
                    hs::Val t = hs::op_add(t, x);
                }
            } else if (__it.is_str()) {
                for (size_t __n = 0; __n < __it.sv.size(); __n++) {
                    hs::Val x = hs::Val::text(std::string(1, __it.sv[__n]));
                    hs::Val t = hs::op_add(t, x);
                }
            } else {
                hs::Val x = __it;
                hs::Val t = hs::op_add(t, x);
            }
        }
        return hs::hs_respond(t);
        return hs::Response::error(500, "route reached the end without returning a value");
    } catch (const hs::HttpAbort& a) {
        return a.r;
    } catch (const std::exception& e) {
        return hs::Response::error(500, std::string("route error: ") + e.what());
    }
}

int main(int argc, char** argv) {
    hs::set_args(argc, argv);
    hs::Server app;
    hs::hs_set_server(&app);
    app.handle("GET", "/", route_0);
    app.port = hs::port_from_env(3031);

    app.listen();
    return 0;
}
