// Generated by the HardScript compiler — do not edit.
#include "hs_runtime.hpp"
using namespace hs;
using std::string;

static hs::Response route_0(const hs::Request& req) {
    try {
        return hs::hs_respond(([](const hs::Val& __m) -> hs::Val { if (hs::op_eq(__m, hs::Val::int_(1)).bv) return hs::Val::text("one"); return hs::Val::text("other"); return hs::Val::nil(); })(hs::Val::int_(99)));
        return hs::Response::error(500, "route reached the end without returning a value");
    } catch (const hs::HttpAbort& a) {
        return a.r;
    } catch (const std::exception& e) {
        return hs::Response::error(500, std::string("route error: ") + e.what());
    }
}

int main(int argc, char** argv) {
    hs::set_args(argc, argv);
    hs::Server app;
    hs::hs_set_server(&app);
    app.handle("GET", "/", route_0);
    app.port = 3031;

    app.listen();
    return 0;
}
