// Generated by the HardScript compiler — do not edit.
#include "hs_runtime.hpp"
using namespace hs;
using std::string;

static hs::Val fn_slow(const hs::Val& x) {
    return x;
    return hs::Val::nil();
}

static hs::Response route_0(const hs::Request& req) {
    try {
        hs::Val a = fn_slow(hs::Val::int_(6));
        (void)hs::race_val({ []() -> hs::Val { return fn_slow(hs::Val::int_(1)); }, []() -> hs::Val { return hs::Val::int_(2); } });
        return hs::Response::error(500, "route reached the end without returning a value");
    } catch (const hs::HttpAbort& a) {
        return a.r;
    } catch (const std::exception& e) {
        return hs::Response::error(500, std::string("route error: ") + e.what());
    }
}

int main(int argc, char** argv) {
    hs::set_args(argc, argv);
    hs::Server app;
    hs::hs_set_server(&app);
    app.handle("GET", "/", route_0);
    app.port = hs::port_from_env(3031);

    app.listen();
    return 0;
}
