// Generated by the HardScript compiler — do not edit.
#include "hs_runtime.hpp"
using namespace hs;
using std::string;

static hs::Response route_0(const hs::Request& req) {
    try {
        hs::expect(hs::op_eq(hs::Val::int_(1), hs::Val::int_(1)) .bv, "expect 1 == 1", "prog.hard:3");
        hs::expect(hs::op_eq(hs::op_add(hs::Val::text("a"), hs::Val::text("b")), hs::Val::text("ab")) .bv, "expect \"a\" + \"b\" == \"ab\"", "prog.hard:4");
        return hs::hs_respond(hs::Val::int_(1));
        return hs::Response::error(500, "route reached the end without returning a value");
    } catch (const std::exception& e) {
        return hs::Response::error(500, std::string("route error: ") + e.what());
    }
}

int main(int argc, char** argv) {
    hs::set_args(argc, argv);
    hs::Server app;
    hs::hs_set_server(&app);
    app.handle("GET", "/", route_0);
    app.port = 3031;

    app.listen();
    return 0;
}
