// Generated by the HardScript compiler — do not edit.
#include "hs_runtime.hpp"
using namespace hs;
using std::string;

static hs::Response route_0(const hs::Request& req) {
    try {
        hs::Val o = hs::Val::object({ {"a", hs::Val::object({ {"b", hs::Val::list(std::vector<hs::Val>{ hs::Val::int_(10), hs::Val::int_(20), hs::Val::int_(30) })} })} });
        return hs::hs_respond(hs::index_at(hs::get_member(hs::get_member(o, "a"), "b"), hs::Val::int_(2)));
        return hs::Response::error(500, "route reached the end without returning a value");
    } catch (const hs::HttpAbort& a) {
        return a.r;
    } catch (const std::exception& e) {
        return hs::Response::error(500, std::string("route error: ") + e.what());
    }
}

int main(int argc, char** argv) {
    hs::set_args(argc, argv);
    hs::Server app;
    hs::hs_set_server(&app);
    app.handle("GET", "/", route_0);
    app.port = 3031;

    app.listen();
    return 0;
}
