// Generated by the HardScript compiler — do not edit.
#include "hs_runtime.hpp"
using namespace hs;
using std::string;

static hs::Response route_0(const hs::Request& req) {
    try {
        (void)(([&]() -> hs::Val { hs::fs_write(hs::to_text(hs::Val::text("/tmp/hs_snap.txt")).sv, hs::to_text(hs::Val::text("snap")).sv); return hs::Val::nil(); }()));
        return hs::hs_respond(hs::Val::text(hs::fs_read(hs::to_text(hs::Val::text("/tmp/hs_snap.txt")).sv)));
        return hs::Response::error(500, "route reached the end without returning a value");
    } catch (const std::exception& e) {
        return hs::Response::error(500, std::string("route error: ") + e.what());
    }
}

int main(int argc, char** argv) {
    hs::set_args(argc, argv);
    hs::Server app;
    hs::hs_set_server(&app);
    app.handle("GET", "/", route_0);
    app.port = 3031;

    app.listen();
    return 0;
}
