//! Deterministic `hard.lock`.
//!
//! The lockfile records the exact resolution: every resolved version, its
//! integrity hash, its dependency tree, plus the compiler/CLI version and
//! platform metadata that produced it. For identical inputs the lockfile
//! bytes are identical (all collection ordering is canonical).

use crate::resolver::Resolution;
use crate::semver::Version;
use std::collections::BTreeMap;

pub const LOCKFILE_SCHEMA: &str = "hard-lock/v1";

/// One locked package entry.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct LockedPackage {
    pub name: String,
    pub version: Version,
    /// SHA-256 integrity of the package archive (`sha256:<hex>`).
    pub integrity: Option<String>,
    /// Dependency names, in sorted order.
    pub deps: Vec<String>,
    pub source: String,
}

/// A parsed/representable lockfile.
#[derive(Clone, Debug, Default)]
pub struct Lockfile {
    pub schema: String,
    pub toolchain: String,
    pub compiler_version: String,
    pub platform: String,
    pub packages: Vec<LockedPackage>,
}

impl Lockfile {
    /// Build a lockfile from a resolution plus toolchain metadata.
    pub fn from_resolution(
        resolution: &Resolution,
        toolchain: &str,
        compiler_version: &str,
        platform: &str,
    ) -> Lockfile {
        let mut packages: Vec<LockedPackage> = resolution
            .packages
            .iter()
            .map(|p| LockedPackage {
                name: p.name.clone(),
                version: p.version.clone(),
                integrity: p.integrity.clone(),
                deps: p.deps.clone(),
                source: match p.source {
                    crate::resolver::SourceKind::Registry => "registry".to_string(),
                    crate::resolver::SourceKind::Workspace => "workspace".to_string(),
                },
            })
            .collect();
        // Packages are emitted sorted by (source, name, version) so identical
        // input sets always produce the same file regardless of traversal.
        packages.sort_by(|a, b| {
            a.source
                .cmp(&b.source)
                .then_with(|| a.name.cmp(&b.name))
                .then_with(|| a.version.cmp(&b.version))
        });
        Lockfile {
            schema: LOCKFILE_SCHEMA.to_string(),
            toolchain: toolchain.to_string(),
            compiler_version: compiler_version.to_string(),
            platform: platform.to_string(),
            packages,
        }
    }

    /// Render the lockfile to canonical text (deterministic).
    pub fn render(&self) -> String {
        let mut s = String::new();
        s.push_str(&format!(
            "# hard.lock — resolved dependency tree (generated by {})\n",
            self.toolchain
        ));
        s.push_str(&format!("schema = \"{}\"\n", self.schema));
        s.push_str(&format!("compiler = \"{}\"\n", self.compiler_version));
        s.push_str(&format!("platform = \"{}\"\n", self.platform));
        s.push('\n');
        for p in &self.packages {
            s.push_str(&format!("[package.{}]\n", p.name));
            s.push_str(&format!("version = \"{}\"\n", p.version));
            if let Some(i) = &p.integrity {
                s.push_str(&format!("integrity = \"{i}\"\n"));
            }
            if !p.deps.is_empty() {
                let deps: Vec<String> = p.deps.iter().map(|d| format!("\"{}\"", escape(d))).collect();
                s.push_str(&format!("dependencies = [{}]\n", deps.join(", ")));
            }
            s.push_str(&format!("source = \"{}\"\n", p.source));
            s.push('\n');
        }
        s
    }

    /// Parse lockfile text. Returns an Err message on structural problems.
    pub fn parse(src: &str) -> Result<Lockfile, String> {
        let doc = crate::toml::parse(src).map_err(|diags| {
            if let Some(d) = diags.first() {
                format!("line {}:{}: {}", d.line, d.col, d.message)
            } else {
                "invalid hard.lock".to_string()
            }
        })?;
        let schema = doc
            .get("schema")
            .and_then(|v| v.as_str())
            .ok_or("hard.lock is missing 'schema'")?;
        if schema != LOCKFILE_SCHEMA {
            return Err(format!("unsupported lockfile schema '{schema}'"));
        }
        let compiler_version = doc
            .get("compiler")
            .and_then(|v| v.as_str())
            .unwrap_or("")
            .to_string();
        let platform = doc
            .get("platform")
            .and_then(|v| v.as_str())
            .unwrap_or("")
            .to_string();
        let tbl = doc.table("package").ok_or("hard.lock has no packages")?;
        let mut packages = Vec::new();
        for (name, t) in tbl {
            let t = t.as_table().ok_or_else(|| {
                format!("package '{name}' is not a table in hard.lock")
            })?;
            let version = t
                .get("version")
                .and_then(|v| v.as_str())
                .ok_or_else(|| format!("package '{name}' has no version"))?;
            let version = Version::parse(version).map_err(|e| format!("package '{name}': {e}"))?;
            let integrity = t
                .get("integrity")
                .and_then(|v| v.as_str())
                .map(String::from);
            let deps = t
                .get("dependencies")
                .and_then(|v| v.as_array())
                .map(|arr| {
                    arr.iter()
                        .filter_map(|i| i.as_str().map(String::from))
                        .collect::<Vec<_>>()
                })
                .unwrap_or_default();
            let source = t
                .get("source")
                .and_then(|v| v.as_str())
                .unwrap_or("registry")
                .to_string();
            packages.push(LockedPackage {
                name: name.clone(),
                version,
                integrity,
                deps,
                source,
            });
        }
        packages.sort_by(|a, b| a.name.cmp(&b.name));
        Ok(Lockfile {
            schema: schema.to_string(),
            toolchain: String::new(),
            compiler_version,
            platform,
            packages,
        })
    }

    /// The locked version of `name`, if present.
    pub fn version_of(&self, name: &str) -> Option<&Version> {
        self.packages.iter().find(|p| p.name == name).map(|p| &p.version)
    }

    /// A `name -> version` map for quick lookups.
    pub fn as_map(&self) -> BTreeMap<String, Version> {
        self.packages
            .iter()
            .map(|p| (p.name.clone(), p.version.clone()))
            .collect()
    }
}

fn escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
#[cfg(test)]
mod tests {
    use super::*;
    use crate::semver::Version;

    #[test]
    fn parse_and_render_roundtrip() {
        let src = r#"schema = "hard-lock/v1"
compiler = "0.4.0-alpha"
platform = "linux-x86_64"

[package.lib]
version = "2.4.0"
source = "registry"
integrity = "sha256:abc"
dependencies = ["mini"]

[package.mini]
version = "0.3.1"
source = "registry"
dependencies = []
"#;
        let lf = Lockfile::parse(src).unwrap();
        assert_eq!(lf.schema, "hard-lock/v1");
        assert_eq!(lf.packages.len(), 2);
        let lib = lf.packages.iter().find(|p| p.name == "lib").unwrap();
        assert_eq!(lib.version.tuple(), (2, 4, 0));
        assert_eq!(lib.deps, vec!["mini"]);
        let rendered = lf.render();
        let reparsed = Lockfile::parse(&rendered).unwrap();
        assert_eq!(reparsed.packages.len(), 2);
        assert_eq!(reparsed.version_of("lib").map(|v| v.tuple()), Some((2, 4, 0)));
    }

    #[test]
    fn sorts_packages_deterministically() {
        let mut lf = Lockfile {
            schema: "hard-lock/v1".into(),
            toolchain: "hard".into(),
            compiler_version: "0.4.0-alpha".into(),
            platform: "linux-x86_64".into(),
            packages: vec![
                LockedPackage {
                    name: "zzz".into(),
                    version: Version::parse("1.0.0").unwrap(),
                    source: "registry".into(),
                    integrity: None,
                    deps: Vec::new(),
                },
                LockedPackage {
                    name: "aaa".into(),
                    version: Version::parse("1.0.0").unwrap(),
                    source: "registry".into(),
                    integrity: None,
                    deps: Vec::new(),
                },
            ],
        };
        lf.packages.sort_by(|a, b| a.name.cmp(&b.name));
        let rendered = lf.render();
        assert!(rendered.find("[package.aaa]").unwrap() < rendered.find("[package.zzz]").unwrap());
    }

    #[test]
    fn malformed_lock_is_rejected() {
        let err = Lockfile::parse("this is not toml [").unwrap_err();
        assert!(!err.is_empty());
    }
}
