//! Deterministic `hard.lock`.
//!
//! The lockfile records the exact resolution: every resolved version, its
//! integrity hash, its dependency tree, plus the compiler/CLI version and
//! platform metadata that produced it. For identical inputs the lockfile
//! bytes are identical (all collection ordering is canonical).
//!
//! Since v1 it also records *trust*: the signature, key id and manifest
//! fingerprint of every registry package, and whether that signature was
//! verified against the local trust store. All four fields are optional, so a
//! lockfile written by an older `hard` still parses, and one written by a newer
//! `hard` still loads on an older one (which ignores what it does not know).

use crate::resolver::Resolution;
use crate::semver::Version;
use std::collections::BTreeMap;

pub const LOCKFILE_SCHEMA: &str = "hard-lock/v1";

/// One locked package entry.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct LockedPackage {
    pub name: String,
    pub version: Version,
    /// SHA-256 integrity of the package archive (`sha256:<hex>`).
    pub integrity: Option<String>,
    /// Dependency names, in sorted order.
    pub deps: Vec<String>,
    pub source: String,
    /// Ed25519 signature over the canonical publish payload, base64.
    pub signature: Option<String>,
    /// The key id that produced the signature, e.g. `k:0123456789abcdef`.
    pub key_id: Option<String>,
    /// The manifest fingerprint the signature covers.
    pub fingerprint: Option<String>,
    /// Whether that signature verified against the local trust store.
    pub verified: bool,
}

impl LockedPackage {
    /// Is this entry's trust information present?
    pub fn has_signature(&self) -> bool {
        self.signature.is_some() && self.key_id.is_some()
    }

    /// Attach trust information from a verification.
    pub fn with_trust(
        &mut self,
        signature: Option<&str>,
        key_id: Option<&str>,
        fingerprint: Option<&str>,
        verified: bool,
    ) -> &mut LockedPackage {
        if let Some(s) = signature {
            self.signature = Some(s.to_string());
        }
        if let Some(k) = key_id {
            self.key_id = Some(k.to_string());
        }
        if let Some(f) = fingerprint {
            self.fingerprint = Some(f.to_string());
        }
        self.verified = verified;
        self
    }
}

/// A parsed/representable lockfile.
#[derive(Clone, Debug, Default)]
pub struct Lockfile {
    pub schema: String,
    pub toolchain: String,
    pub compiler_version: String,
    pub platform: String,
    pub packages: Vec<LockedPackage>,
}

impl Lockfile {
    /// Build a lockfile from a resolution plus toolchain metadata.
    pub fn from_resolution(
        resolution: &Resolution,
        toolchain: &str,
        compiler_version: &str,
        platform: &str,
    ) -> Lockfile {
        let mut packages: Vec<LockedPackage> = resolution
            .packages
            .iter()
            .map(|p| LockedPackage {
                name: p.name.clone(),
                version: p.version.clone(),
                integrity: p.integrity.clone(),
                deps: p.deps.clone(),
                source: match p.source {
                    crate::resolver::SourceKind::Registry => "registry".to_string(),
                    crate::resolver::SourceKind::Workspace => "workspace".to_string(),
                },
                signature: p.signature.clone(),
                key_id: p.key_id.clone(),
                fingerprint: p.fingerprint.clone(),
                verified: p.verified,
            })
            .collect();
        // Packages are emitted sorted by (source, name, version) so identical
        // input sets always produce the same file regardless of traversal.
        packages.sort_by(|a, b| {
            a.source
                .cmp(&b.source)
                .then_with(|| a.name.cmp(&b.name))
                .then_with(|| a.version.cmp(&b.version))
        });
        Lockfile {
            schema: LOCKFILE_SCHEMA.to_string(),
            toolchain: toolchain.to_string(),
            compiler_version: compiler_version.to_string(),
            platform: platform.to_string(),
            packages,
        }
    }

    /// Render the lockfile to canonical text (deterministic).
    pub fn render(&self) -> String {
        let mut s = String::new();
        s.push_str(&format!(
            "# hard.lock — resolved dependency tree (generated by {})\n",
            self.toolchain
        ));
        s.push_str(&format!("schema = \"{}\"\n", self.schema));
        s.push_str(&format!("compiler = \"{}\"\n", self.compiler_version));
        s.push_str(&format!("platform = \"{}\"\n", self.platform));
        s.push('\n');
        for p in &self.packages {
            s.push_str(&format!("[package.{}]\n", p.name));
            s.push_str(&format!("version = \"{}\"\n", p.version));
            if let Some(i) = &p.integrity {
                s.push_str(&format!("integrity = \"{i}\"\n"));
            }
            // Trust fields are written only when there is something to record,
            // so a lockfile for a workspace with no registry packages keeps
            // exactly the bytes it had before signatures existed.
            if p.has_signature() || p.verified {
                if let Some(sig) = &p.signature {
                    s.push_str(&format!("signature = \"{}\"\n", escape(sig)));
                }
                if let Some(k) = &p.key_id {
                    s.push_str(&format!("key_id = \"{}\"\n", escape(k)));
                }
                if let Some(f) = &p.fingerprint {
                    s.push_str(&format!("fingerprint = \"{}\"\n", escape(f)));
                }
                s.push_str(&format!("verified = {}\n", p.verified));
            }
            if !p.deps.is_empty() {
                let deps: Vec<String> = p.deps.iter().map(|d| format!("\"{}\"", escape(d))).collect();
                s.push_str(&format!("dependencies = [{}]\n", deps.join(", ")));
            }
            s.push_str(&format!("source = \"{}\"\n", p.source));
            s.push('\n');
        }
        s
    }

    /// Parse lockfile text. Returns an Err message on structural problems.
    pub fn parse(src: &str) -> Result<Lockfile, String> {
        let doc = crate::toml::parse(src).map_err(|diags| {
            if let Some(d) = diags.first() {
                format!("line {}:{}: {}", d.line, d.col, d.message)
            } else {
                "invalid hard.lock".to_string()
            }
        })?;
        let schema = doc
            .get("schema")
            .and_then(|v| v.as_str())
            .ok_or("hard.lock is missing 'schema'")?;
        if schema != LOCKFILE_SCHEMA {
            return Err(format!("unsupported lockfile schema '{schema}'"));
        }
        let compiler_version = doc
            .get("compiler")
            .and_then(|v| v.as_str())
            .unwrap_or("")
            .to_string();
        let platform = doc
            .get("platform")
            .and_then(|v| v.as_str())
            .unwrap_or("")
            .to_string();
        let tbl = doc.table("package").ok_or("hard.lock has no packages")?;
        let mut packages = Vec::new();
        for (name, t) in tbl {
            let t = t.as_table().ok_or_else(|| {
                format!("package '{name}' is not a table in hard.lock")
            })?;
            let version = t
                .get("version")
                .and_then(|v| v.as_str())
                .ok_or_else(|| format!("package '{name}' has no version"))?;
            let version = Version::parse(version).map_err(|e| format!("package '{name}': {e}"))?;
            let integrity = t
                .get("integrity")
                .and_then(|v| v.as_str())
                .map(String::from);
            let deps = t
                .get("dependencies")
                .and_then(|v| v.as_array())
                .map(|arr| {
                    arr.iter()
                        .filter_map(|i| i.as_str().map(String::from))
                        .collect::<Vec<_>>()
                })
                .unwrap_or_default();
            let source = t
                .get("source")
                .and_then(|v| v.as_str())
                .unwrap_or("registry")
                .to_string();
            // All four are optional: a lockfile from before signature support
            // parses unchanged, and the entry is simply unverified.
            let signature = t
                .get("signature")
                .and_then(|v| v.as_str())
                .map(String::from);
            let key_id = t.get("key_id").and_then(|v| v.as_str()).map(String::from);
            let fingerprint = t
                .get("fingerprint")
                .and_then(|v| v.as_str())
                .map(String::from);
            let verified = t.get("verified").and_then(|v| v.as_bool()).unwrap_or(false);
            packages.push(LockedPackage {
                name: name.clone(),
                version,
                integrity,
                deps,
                source,
                signature,
                key_id,
                fingerprint,
                verified,
            });
        }
        packages.sort_by(|a, b| a.name.cmp(&b.name));
        Ok(Lockfile {
            schema: schema.to_string(),
            toolchain: String::new(),
            compiler_version,
            platform,
            packages,
        })
    }

    /// The locked version of `name`, if present.
    pub fn version_of(&self, name: &str) -> Option<&Version> {
        self.packages.iter().find(|p| p.name == name).map(|p| &p.version)
    }

    /// A `name -> version` map for quick lookups.
    pub fn as_map(&self) -> BTreeMap<String, Version> {
        self.packages
            .iter()
            .map(|p| (p.name.clone(), p.version.clone()))
            .collect()
    }
}

fn escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
#[cfg(test)]
mod tests {
    use super::*;
    use crate::semver::Version;

    #[test]
    fn parse_and_render_roundtrip() {
        let src = r#"schema = "hard-lock/v1"
compiler = "0.4.0-alpha"
platform = "linux-x86_64"

[package.lib]
version = "2.4.0"
source = "registry"
integrity = "sha256:abc"
dependencies = ["mini"]

[package.mini]
version = "0.3.1"
source = "registry"
dependencies = []
"#;
        let lf = Lockfile::parse(src).unwrap();
        assert_eq!(lf.schema, "hard-lock/v1");
        assert_eq!(lf.packages.len(), 2);
        let lib = lf.packages.iter().find(|p| p.name == "lib").unwrap();
        assert_eq!(lib.version.tuple(), (2, 4, 0));
        assert_eq!(lib.deps, vec!["mini"]);
        let rendered = lf.render();
        let reparsed = Lockfile::parse(&rendered).unwrap();
        assert_eq!(reparsed.packages.len(), 2);
        assert_eq!(reparsed.version_of("lib").map(|v| v.tuple()), Some((2, 4, 0)));
    }

    #[test]
    fn sorts_packages_deterministically() {
        let mut lf = Lockfile {
            schema: "hard-lock/v1".into(),
            toolchain: "hard".into(),
            compiler_version: "0.4.0-alpha".into(),
            platform: "linux-x86_64".into(),
            packages: vec![
                LockedPackage {
                    name: "zzz".into(),
                    version: Version::parse("1.0.0").unwrap(),
                    source: "registry".into(),
                    integrity: None,
                    deps: Vec::new(),
                    signature: None,
                    key_id: None,
                    fingerprint: None,
                    verified: false,
                },
                LockedPackage {
                    name: "aaa".into(),
                    version: Version::parse("1.0.0").unwrap(),
                    source: "registry".into(),
                    integrity: None,
                    deps: Vec::new(),
                    signature: None,
                    key_id: None,
                    fingerprint: None,
                    verified: false,
                },
            ],
        };
        lf.packages.sort_by(|a, b| a.name.cmp(&b.name));
        let rendered = lf.render();
        assert!(rendered.find("[package.aaa]").unwrap() < rendered.find("[package.zzz]").unwrap());
    }

    #[test]
    fn trust_fields_round_trip() {
        let lf = Lockfile {
            schema: LOCKFILE_SCHEMA.into(),
            toolchain: "hard".into(),
            compiler_version: "0.5.0".into(),
            platform: "linux-x86_64".into(),
            packages: vec![LockedPackage {
                name: "jwt".into(),
                version: Version::parse("1.0.0").unwrap(),
                source: "registry".into(),
                integrity: Some("sha256:aa".into()),
                deps: Vec::new(),
                signature: Some("c2ln".into()),
                key_id: Some("k:0123456789abcdef".into()),
                fingerprint: Some("sha256:bb".into()),
                verified: true,
            }],
        };
        let text = lf.render();
        assert!(text.contains("signature = \"c2ln\""), "{text}");
        assert!(text.contains("key_id = \"k:0123456789abcdef\""), "{text}");
        assert!(text.contains("fingerprint = \"sha256:bb\""), "{text}");
        assert!(text.contains("verified = true"), "{text}");
        let back = Lockfile::parse(&text).unwrap();
        assert_eq!(back.packages[0].signature.as_deref(), Some("c2ln"));
        assert_eq!(back.packages[0].key_id.as_deref(), Some("k:0123456789abcdef"));
        assert_eq!(back.packages[0].fingerprint.as_deref(), Some("sha256:bb"));
        assert!(back.packages[0].verified);
        assert!(back.packages[0].has_signature());
        // and the re-render is byte-identical below the generated-by comment,
        // which `parse` deliberately does not recover
        let body = |s: &str| s.lines().skip(1).collect::<Vec<_>>().join("\n");
        assert_eq!(body(&back.render()), body(&text));
    }

    #[test]
    fn a_lockfile_without_trust_fields_still_parses() {
        // exactly what an older `hard` wrote
        let text = "schema = \"hard-lock/v1\"\ncompiler = \"0.4.0\"\nplatform = \"linux\"\n\n[package.lib]\nversion = \"1.0.0\"\nintegrity = \"sha256:abc\"\nsource = \"registry\"\n";
        let lf = Lockfile::parse(text).unwrap();
        let p = &lf.packages[0];
        assert!(p.signature.is_none());
        assert!(p.key_id.is_none());
        assert!(p.fingerprint.is_none());
        assert!(!p.verified);
        assert!(!p.has_signature());
        // and re-rendering does not invent trust fields
        let out = lf.render();
        assert!(!out.contains("signature"), "{out}");
        assert!(!out.contains("verified"), "{out}");
        assert!(out.contains("version = \"1.0.0\""), "{out}");
    }

    #[test]
    fn verified_false_is_recorded_when_a_signature_exists() {
        let lf = Lockfile {
            schema: LOCKFILE_SCHEMA.into(),
            toolchain: "hard".into(),
            compiler_version: "0.5.0".into(),
            platform: "linux".into(),
            packages: vec![LockedPackage {
                name: "jwt".into(),
                version: Version::parse("1.0.0").unwrap(),
                source: "registry".into(),
                integrity: Some("sha256:aa".into()),
                deps: Vec::new(),
                signature: Some("c2ln".into()),
                key_id: Some("k:1".into()),
                fingerprint: None,
                verified: false,
            }],
        };
        let text = lf.render();
        assert!(text.contains("verified = false"), "{text}");
        assert!(!text.contains("fingerprint"), "absent fields stay absent");
        let back = Lockfile::parse(&text).unwrap();
        assert!(!back.packages[0].verified);
        assert!(back.packages[0].has_signature());
        assert_eq!(lf.render(), text);
    }

    #[test]
    fn with_trust_attaches_and_merges() {
        let mut p = LockedPackage {
            name: "jwt".into(),
            version: Version::parse("1.0.0").unwrap(),
            source: "registry".into(),
            integrity: None,
            deps: Vec::new(),
            signature: None,
            key_id: None,
            fingerprint: None,
            verified: false,
        };
        p.with_trust(Some("c2ln"), Some("k:1"), Some("sha256:aa"), true);
        assert!(p.has_signature());
        assert!(p.verified);
        p.with_trust(None, None, Some("sha256:bb"), false);
        assert_eq!(p.fingerprint.as_deref(), Some("sha256:bb"));
        assert_eq!(p.signature.as_deref(), Some("c2ln"), "nothing is cleared");
        assert!(!p.verified);
    }

    #[test]
    fn malformed_lock_is_rejected() {
        let err = Lockfile::parse("this is not toml [").unwrap_err();
        assert!(!err.is_empty());
    }
}
