//! Ecosystem reports: markdown summaries written to `reports/`.
//!
//! Each report is deterministic (sorted, fixed-width) so it can be asserted
//! on in CI.

use crate::cache::Cache;
use crate::templates::all;
use crate::workspace::Workspace;
use std::path::Path;

/// A single report to be written.
pub struct Report {
    pub name: &'static str,
    pub title: String,
    pub body: String,
}

fn header(title: &str) -> String {
    format!(
        "# {title}\n\n_Generated by `hard report`. Do not edit — regenerated on demand._\n\n"
    )
}

fn measures_table(items: &[(&str, &str)]) -> String {
    let mut out = String::from("\n| metric | value |\n|--------|-------|\n");
    for (k, v) in items {
        out.push_str(&format!("| {k} | `{v}` |\n"));
    }
    out
}

fn lines(code_block: &[String]) -> String {
    let mut out = String::from("```\n");
    for l in code_block {
        out.push_str(l);
        out.push('\n');
    }
    out.push_str("```\n");
    out
}

/// Build every report. Cheap to call; nothing is written here.
pub fn build(cache: &Cache) -> Vec<Report> {
    vec![
        package_manager_report(),
        dependency_resolver_report(),
        cache_report(cache),
        workspace_report(),
        templates_report(),
    ]
}

fn package_manager_report() -> Report {
    let mut body = header("Package Manager Report");
    body.push_str(
        "## Overview\n\n\
         M4.0 introduces the HardScript package manager: a dependency registry\n\
         client (no server ships yet), deterministic resolver, shared cache and\n\
         `hard add / remove / install / update / list / outdated / search / info`.\n",
    );
    body.push_str(
        "\n## Commands\n\
         \n| command | role |\n|---------|-----|\n\
         | `hard init` | scaffold a manifest in the current directory |\n\
         | `hard new <name>` | scaffold a project or template |\n\
         | `hard add <pkg>` | add + resolve + install a dependency |\n\
         | `hard remove <pkg>` | remove a dependency |\n\
         | `hard install` | install everything in the lockfile |\n\
         | `hard update [pkg]` | bump to newest matching versions |\n\
         | `hard list` | show installed packages |\n\
         | `hard outdated` | show packages with newer releases |\n\
         | `hard search <q>` | search the registry |\n\
         | `hard info <pkg>` | show package metadata |\n",
    );
    body.push_str(
        "\n## Storage\n\
         \n- Manifest: `hard.toml` (schema `1`, `edition \"2027\"`).\n\
         - Lockfile: `hard.lock` (schema `hard-lock/v1`).\n\
         - Cache: `$HARD_HOME/cache` or `~/.hard/cache`.\n\
         - Archive format: `.hspkg` (magic `HSPKG\\0\\x01`), integrity = SHA-256.\n",
    );
    Report {
        name: "package-manager.md",
        title: "Package Manager Report".to_string(),
        body,
    }
}

fn dependency_resolver_report() -> Report {
    let mut body = header("Dependency Resolver Report");
    body.push_str(
        "## Semver\n\n\
         Supported requirement operators: exact `1.2.3`, caret `^1.2`,\n\
         tilde `~1.2.3`, wildcard `1.2.*`, comparator sets `>=1.0,<2`. Prerelease\n\
         versions (`-beta.1`) only match when the requirement itself is a\n\
         prerelease of the same base.\n",
    );
    body.push_str(
        "\n## Resolution\n\n\
         The resolver builds a global index of every known version, then walks\n\
         the graph from the root package in deterministic topological order.\n\
         Conflicts are re-negotiated by reassigning dependency requirements;\n\
         cycles are reported as errors rather than silently broken.\n",
    );
    body.push_str(
        "\n## Errors\n\
         \n| code | meaning |\n|------|---------|\n\
         | `not-found` | package does not exist |\n\
         | `unresolvable` | no version satisfies the requirement |\n\
         | `conflict` | requirements disagree on a package |\n\
         | `duplicate` | same package declared twice |\n\
         | `circular` | dependency cycle detected |\n\
         | `invalid-req` | malformed version requirement |\n",
    );
    Report {
        name: "dependency-resolver.md",
        title: "Dependency Resolver Report".to_string(),
        body,
    }
}

fn cache_report(cache: &Cache) -> Report {
    let root = cache.root.display().to_string();
    let (pkg_count, bytes) = cache.stats();
    let mut body = header("Cache Report");
    body.push_str(&format!("Cache root: `{root}`\n"));
    body.push_str(&measures_table(&[
        ("packages", &pkg_count.to_string()),
        ("bytes", &bytes.to_string()),
    ]));
    body.push_str("\n## Integrity\n\n");
    let report = cache.verify_all();
    if report.is_empty() {
        body.push_str("All cached archives verified against their recorded SHA-256.\n");
    } else {
        body.push_str("The following cached packages failed integrity verification:\n\n");
        let mut lines: Vec<String> = report.iter().map(|s| format!("- {s}")).collect();
        lines.sort();
        for l in lines {
            body.push_str(&l);
            body.push('\n');
        }
    }
    body.push_str("\n## Hygiene\n\n`hard cache clean` removes corrupted archives and stale temp files.\n");
    Report {
        name: "cache-report.md",
        title: "Cache Report".to_string(),
        body,
    }
}

fn workspace_report() -> Report {
    let cwd = std::env::current_dir().unwrap_or_else(|_| Path::new(".").to_path_buf());
    let mut body = header("Workspace Report");
    match Workspace::discover(&cwd, &crate::tui::Logger::silent()) {
        Ok(Some(ws)) => {
            body.push_str(&format!(
                "Workspace root: `{}`\n\nMembers: **{}**\n\n",
                ws.root.display(),
                ws.len()
            ));
            body.push_str(&lines(&ws.list_versions_lines()));
        }
        Ok(None) => {
            body.push_str("No workspace detected from the current directory.\n");
            body.push_str("\nCreate one by adding a `workspace` list to a `hard.toml`:\n\n```toml\nworkspace = [\"apps/a\", \"libs/b\"]\n```\n");
        }
        Err(e) => body.push_str(&format!("**Workspace error:** {e}\n")),
    }
    Report {
        name: "workspace-report.md",
        title: "Workspace Report".to_string(),
        body,
    }
}

fn templates_report() -> Report {
    let mut body = header("Templates Report");
    body.push_str(&format!(
        "Official templates ship with the `hard` binary and need no network.\n\n\
         Count: **{}**\n",
        all().len()
    ));
    body.push_str("\n| template | port | files |\n|----------|------|-------|\n");
    let mut sorted: Vec<_> = all().into_iter().collect();
    sorted.sort_by(|a, b| a.name.cmp(b.name));
    for t in sorted {
        let files: Vec<&str> = t.files.iter().map(|(p, _)| *p).collect();
        body.push_str(&format!("| {} | {} | {} |\n", t.name, t.port, files.join(", ")));
    }
    body.push_str("\nScaffold with `hard new <template>`.\n");
    Report {
        name: "templates-report.md",
        title: "Templates Report".to_string(),
        body,
    }
}

/// Write the reports to `dir` (default `reports`). Returns written paths.
pub fn write_all(cache: &Cache, dir: &Path) -> Result<Vec<String>, String> {
    std::fs::create_dir_all(dir).map_err(|e| format!("cannot create {}: {e}", dir.display()))?;
    let mut written = Vec::new();
    for r in build(cache) {
        let path = dir.join(r.name);
        std::fs::write(&path, r.body.as_bytes())
            .map_err(|e| format!("cannot write {}: {e}", path.display()))?;
        written.push(r.name.to_string());
    }
    Ok(written)
}